### ISSUE TITLE
An error occurred during code testing

### ISSUE THREAD

**Issue by YSYYU** [TQTQliu/ET-MVSNet#17]
Thank you for your excellent work. I encountered the following error message while replicating the DTU test dataset. I hope you can answer it and look forward to your reply.

save_depth(testlist)
  File "/home/featurize/work/ET-MVSNet-main/test_dtu_dypcd.py", line 392, in save_depth
    torch.cuda.reset_peak_memory_stats()
  File "/environment/miniconda3/envs/etmvsnet/lib/python3.10/site-packages/torch/cuda/memory.py", line 309, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
RuntimeError: invalid argument to reset_peak_memory_stats

**Comment by TQTQliu** [comment]
It may be an problem of your environment, you can check the version according to [this](https://github.com/TQTQliu/ET-MVSNet/blob/e29d0b6c1d7772a86b730f4b8b106df3846a7fb2/README.md?plain=1#L17). Also note that torch and cuda versions should be compatible.

**Comment by YSYYU** [comment]
Hello, thank you for your reply. While testing the DTU dataset, I found that the point cloud files obtained during the training process were very strange. Why would they look like the one shown in the following picture?

![20240625172656](https://github.com/TQTQliu/ET-MVSNet/assets/154568097/1e97e31d-824a-464f-9079-bf515f21866a)

**Comment by TQTQliu** [comment]
Do you use a fully trained checkpoint? If you are using a model that has only trained a few epochs, the estimated depths may not accurate enough. If you use a model that has fully trained and use the default fusion hyperparameters, you could get a better point cloud.

**Comment by YSYYU** [comment]
Hello, thank you for your reply. I encountered the following problem when running the test_dtu_dypcd.py code before. It showed that the tensor on the CUDA device could not be processed during numpy conversion. Therefore, I modified your code to move the tensor to the CPU first, and there have been corresponding changes in the future. I am not sure if such changes will affect the results. I hope you can answer the code problem I encountered. Thank you!

Traceback (most recent call last):
  File "/home/featurize/work/ET-MVSNet-main/test_dtu_dypcd.py", line 511, in <module>
    save_depth(testlist)
  File "/home/featurize/work/ET-MVSNet-main/test_dtu_dypcd.py", line 396, in save_depth
    time_this_scene, sample_this_scene = save_scene_depth([scene])
  File "/home/featurize/work/ET-MVSNet-main/test_dtu_dypcd.py", line 434, in save_scene_depth
    outputs = model(sample_cuda["imgs"], sample_cuda["proj_matrices"], sample_cuda["depth_values"],sample['flag'])
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/featurize/work/ET-MVSNet-main/models/MVS4Net.py", line 68, in forward
    depth_hypo = schedule_range(outputs_stage['depth'].detach(), self.stage_splits[stage_idx], self.depth_interals_ratio[stage_idx] * depth_interval, H, W)
  File "/home/featurize/work/ET-MVSNet-main/models/module.py", line 129, in schedule_range
    cur_depth_min = (cur_depth - ndepth / 2 * depth_inteval_pixel[:,None,None])  # (B, H, W)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/_tensor.py", line 956, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by TQTQliu** [comment]
Code errors may be an problem of your environment.
And I think the changes you made will not affect the results.
