### ISSUE TITLE
i met an error when tested data

### ISSUE THREAD

**Issue by yolic66** [TQTQliu/ET-MVSNet#4]
Traceback (most recent call last):
  File "C:\Users\dell\Desktop\ET-MVSNet-main\ET-MVSNet-main\test_dtu_dypcd.py", line 511, in <module>
    save_depth(testlist)
  File "C:\Users\dell\Desktop\ET-MVSNet-main\ET-MVSNet-main\test_dtu_dypcd.py", line 392, in save_depth
    torch.cuda.reset_peak_memory_stats()
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\torch\cuda\memory.py", line 260, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
RuntimeError: invalid argument to reset_peak_memory_stats

**Comment by yolic66** [comment]
solved！change test_dtu.sh 'export CUDA_VISIBLE_DEVICES=1' to 'export CUDA_VISIBLE_DEVICES=0'

**Comment by Ttingyyy** [comment]
do you hava this problem?
![a53d05be325836a57ff39e855ab3585](https://github.com/TQTQliu/ET-MVSNet/assets/130437764/8d1fae05-10c1-4b8d-ab47-e848d19a964a)
为什么会显示数据输入维度有问题？我下载的数据是所给的测试数据集呢
